site_name: Моё портфолио
site_description: Выполненные работы по программированию
site_author: Бойко Мария

nav:
  - Главная: index.md
  - Программирование:
    - 1. Two Sum: programming/work1.md
    - 2. Задача деления: programming/work2.md
    - 3. Бинарное дерево: programming/work3.md
    - 4. Итераторы и сопрограммы: programming/work4.md
    - 5. Паттерн "Декоратор": programming/work5.md
    - 6. Паттерн "Одиночка": programming/work6.md
    - 7. Основные концепции ООП (Перегрузка): programming/work7.md
  - Обо мне: about.md
  - Контакты: contacts.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables
